# Generated by Django 4.2.2 on 2023-06-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prov_apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('prov_dni', models.IntegerField(verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prod_precio', models.FloatField(verbose_name='Precio')),
                ('prod_stock_act', models.IntegerField(verbose_name='Stock_actual')),
                ('prod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='compra.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
